version: '3.9'
services:
  balancer:
    image: 'jwilder/nginx-proxy'
    container_name: nginx-balancer
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: 'no'

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    volumes:
      - ./.:/var/www/html
    hostname: www.blogging-platform-api.com
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=www.blogging-platform-api.com
    user: "${UID:-1000}:${UID:-1000}" 
    restart: 'no'
    depends_on:
      - balancer